using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using CitizenFX.Core;
using CitizenFX.Core.Native;
using JetBrains.Annotations;
using NFive.SDK.Core.Input;

namespace NFive.SDK.Client.Input
{
	[PublicAPI]
	public static class Input
	{
		private static Dictionary<InputModifier, int> ModifierFlagToValue => new Dictionary<InputModifier, int>
		{
			[InputModifier.Ctrl] = 36,
			[InputModifier.Alt] = 19,
			[InputModifier.Shift] = 21
		};

		public static List<ButtonCode> ControlButtonCodeMapping = new List<ButtonCode>
		{
			ButtonCode.Back,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.Right3,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.DpadRight,
			ButtonCode.DpadLeft,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.A,
			ButtonCode.DpadDown,
			ButtonCode.DpadDown,
			ButtonCode.A,
			ButtonCode.X,
			ButtonCode.Y,
			ButtonCode.RightTrigger,
			ButtonCode.LeftTrigger,
			ButtonCode.Right3,
			ButtonCode.DpadUp,
			ButtonCode.Left3,
			ButtonCode.Right3,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.Left3,
			ButtonCode.LeftButton,
			ButtonCode.LeftButton,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.DpadUp,
			ButtonCode.DpadDown,
			ButtonCode.RightButton,
			ButtonCode.B,
			ButtonCode.DpadRight,
			ButtonCode.DpadLeft,
			ButtonCode.DpadDown,
			ButtonCode.Y,
			ButtonCode.Right3,
			ButtonCode.DpadRight,
			ButtonCode.DpadLeft,
			ButtonCode.Y,
			ButtonCode.DpadRight,
			ButtonCode.RightButton,
			ButtonCode.Y,
			ButtonCode.B,
			ButtonCode.DpadLeft,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.None,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.A,
			ButtonCode.RightTrigger,
			ButtonCode.LeftTrigger,
			ButtonCode.A,
			ButtonCode.DpadRight,
			ButtonCode.Y,
			ButtonCode.RightButton,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.Right3,
			ButtonCode.B,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.DpadLeft,
			ButtonCode.Left3,
			ButtonCode.RightTrigger,
			ButtonCode.LeftTrigger,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.Right3,
			ButtonCode.None,
			ButtonCode.RightStick,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.RightStick,
			ButtonCode.X,
			ButtonCode.None,
			ButtonCode.DpadRight,
			ButtonCode.RightButton,
			ButtonCode.DpadRight,
			ButtonCode.DpadRight,
			ButtonCode.A,
			ButtonCode.None,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.Left3,
			ButtonCode.A,
			ButtonCode.DpadLeft,
			ButtonCode.None,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.DpadRight,
			ButtonCode.A,
			ButtonCode.Right3,
			ButtonCode.None,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.RightTrigger,
			ButtonCode.LeftTrigger,
			ButtonCode.X,
			ButtonCode.A,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.None,
			ButtonCode.A,
			ButtonCode.A,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.B,
			ButtonCode.A,
			ButtonCode.RightTrigger,
			ButtonCode.X,
			ButtonCode.Y,
			ButtonCode.Y,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.A,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.B,
			ButtonCode.None,
			ButtonCode.DpadUp,
			ButtonCode.DpadDown,
			ButtonCode.DpadLeft,
			ButtonCode.DpadRight,
			ButtonCode.A,
			ButtonCode.B,
			ButtonCode.Y,
			ButtonCode.X,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.RightTrigger,
			ButtonCode.RightButton,
			ButtonCode.Right3,
			ButtonCode.LeftButton,
			ButtonCode.Left3,
			ButtonCode.DpadDown,
			ButtonCode.DpadUp,
			ButtonCode.DpadLeft,
			ButtonCode.DpadRight,
			ButtonCode.A,
			ButtonCode.Y,
			ButtonCode.X,
			ButtonCode.B,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.Start,
			ButtonCode.None,
			ButtonCode.A,
			ButtonCode.B,
			ButtonCode.X,
			ButtonCode.Y,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.Left3,
			ButtonCode.Right3,
			ButtonCode.RightButton,
			ButtonCode.Back,
			ButtonCode.RightButton,
			ButtonCode.X,
			ButtonCode.A,
			ButtonCode.X,
			ButtonCode.Back,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.Y,
			ButtonCode.A,
			ButtonCode.X,
			ButtonCode.B,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.Left3,
			ButtonCode.Right3,
			ButtonCode.DpadUp,
			ButtonCode.DpadDown,
			ButtonCode.DpadLeft,
			ButtonCode.DpadRight,
			ButtonCode.Back,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.Back,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.Left3,
			ButtonCode.Right3,
			ButtonCode.LeftTrigger,
			ButtonCode.RightTrigger,
			ButtonCode.None,
			ButtonCode.A,
			ButtonCode.X,
			ButtonCode.RightTrigger,
			ButtonCode.A,
			ButtonCode.X,
			ButtonCode.RightTrigger,
			ButtonCode.DpadLeft,
			ButtonCode.DpadRight,
			ButtonCode.B,
			ButtonCode.A,
			ButtonCode.None,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.A,
			ButtonCode.X,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.X,
			ButtonCode.Y,
			ButtonCode.A,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.A,
			ButtonCode.None,
			ButtonCode.DpadUp,
			ButtonCode.Right3,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.DpadRight,
			ButtonCode.DpadLeft,
			ButtonCode.DpadDown,
			ButtonCode.Back,
			ButtonCode.DpadDown,
			ButtonCode.DpadLeft,
			ButtonCode.DpadRight,
			ButtonCode.RightButton,
			ButtonCode.LeftButton,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.Start,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.RightTrigger,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.None,
			ButtonCode.RightStick,
			ButtonCode.RightStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.A,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.LeftStick,
			ButtonCode.DpadRight,
			ButtonCode.A,
			ButtonCode.LeftButton,
			ButtonCode.RightButton,
			ButtonCode.Y,
			ButtonCode.X,
			ButtonCode.Left3,
			ButtonCode.Left3,
			ButtonCode.Left3,
			ButtonCode.A,
			ButtonCode.A,
			ButtonCode.DpadRight,
			ButtonCode.DpadRight,
			ButtonCode.A
		};

		// Generated from v1737 in English with QWERTY
		public static List<KeyCode> ControlKeyCodeMapping = new List<KeyCode>
		{
			KeyCode.KeyV,
			KeyCode.MouseMoveLeftRight,
			KeyCode.MouseMoveUpDown,
			KeyCode.MouseMoveUp,
			KeyCode.MouseMoveDown,
			KeyCode.MouseMoveLeft,
			KeyCode.MouseMoveRight,
			KeyCode.KeyL,
			KeyCode.KeyWKeyS,
			KeyCode.KeyAKeyD,
			KeyCode.PageUp,
			KeyCode.PageDown,
			KeyCode.MouseMoveUpDown, // No scaleform
            KeyCode.MouseMoveLeftRight, // No scaleform
            KeyCode.MouseWheelDown,
			KeyCode.MouseWheelUp,
			KeyCode.MouseWheelDown,
			KeyCode.MouseWheelUp,
			KeyCode.MouseLeftClick, // KeyCode.Return / KeyCode.Space
            KeyCode.AltLeft,
			KeyCode.KeyZ,
			KeyCode.ShiftLeft,
			KeyCode.Space,
			KeyCode.KeyF,
			KeyCode.MouseLeftClick,
			KeyCode.MouseRightClick,
			KeyCode.KeyC,
			KeyCode.ArrowUp, // KeyCode.MouseWheelClick
            KeyCode.None,
			KeyCode.KeyB, // _SECONDARY
            KeyCode.KeyAKeyD,
			KeyCode.KeyWKeyS,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.ControlLeft,
			KeyCode.Tab,
			KeyCode.KeyE,
			KeyCode.MouseWheelUpDown,
			KeyCode.MouseWheelUp,
			KeyCode.MouseWheelDown,
			KeyCode.BracketRight, // _SECONDARY
            KeyCode.BracketLeft, // _SECONDARY
            KeyCode.KeyQ,
			KeyCode.KeyR,
			KeyCode.KeyE,
			KeyCode.KeyG,
			KeyCode.KeyZ,
			KeyCode.KeyF,
			KeyCode.MouseWheelUpDown,
			KeyCode.KeyE,
			KeyCode.KeyQ, // _SECONDARY
            KeyCode.None,
			KeyCode.KeyE,
			KeyCode.Space,
			KeyCode.F9,
			KeyCode.F10,
			KeyCode.KeyG,
			KeyCode.KeyAKeyD,
			KeyCode.LeftShiftLeftControl,
			KeyCode.ShiftLeft,
			KeyCode.ControlLeft,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.None,
			KeyCode.MouseMoveLeftRight,
			KeyCode.MouseMoveUpDown,
			KeyCode.MouseRightClick,
			KeyCode.MouseLeftClick,
			KeyCode.ControlRight,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.KeyX,
			KeyCode.KeyH,
			KeyCode.KeyF,
			KeyCode.Space,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.KeyC,
			KeyCode.KeyR,
			KeyCode.Period,
			KeyCode.Comma,
			KeyCode.Equal,
			KeyCode.Minus,
			KeyCode.KeyQ,
			KeyCode.KeyE,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.MouseRightClick,
			KeyCode.MouseLeftClick,
			KeyCode.None,
			KeyCode.None,
			KeyCode.MouseMoveUpDown,
			KeyCode.MouseWheelUp, // KeyCode.PageUp
            KeyCode.MouseWheelDown, // KeyCode.PageDown 
            KeyCode.MouseMoveLeftRight,
			KeyCode.MouseWheelUp,
			KeyCode.BracketLeft,
			KeyCode.KeyH,
			KeyCode.Space,
			KeyCode.KeyE,
			KeyCode.KeyH,
			KeyCode.KeyX,
			KeyCode.MouseLeftClick,
			KeyCode.Numpad4Numpad6,
			KeyCode.Numpad4,
			KeyCode.Numpad6,
			KeyCode.Numpad8Numpad5,
			KeyCode.Numpad8,
			KeyCode.Numpad5,
			KeyCode.KeyG,
			KeyCode.Space,
			KeyCode.MouseWheelUp,
			KeyCode.BracketLeft,
			KeyCode.Numpad7,
			KeyCode.Numpad9,
			KeyCode.KeyE,
			KeyCode.KeyX,
			KeyCode.Insert,
			KeyCode.MouseLeftClick,
			KeyCode.Numpad4Numpad6,
			KeyCode.Numpad4,
			KeyCode.Numpad6,
			KeyCode.Numpad8Numpad5,
			KeyCode.Numpad8,
			KeyCode.Numpad5,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.ShiftLeft,
			KeyCode.ControlLeft,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.MouseLeftClick,
			KeyCode.KeyW,
			KeyCode.CapsLock,
			KeyCode.KeyQ,
			KeyCode.KeyS,
			KeyCode.KeyR,
			KeyCode.KeyQ,
			KeyCode.MouseLeftClick,
			KeyCode.Space,
			KeyCode.MouseLeftClick, // KeyCode.F
            KeyCode.KeyF,
			KeyCode.KeyAKeyD,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.KeyWKeyS,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.KeyQ,
			KeyCode.KeyE,
			KeyCode.KeyX,
			KeyCode.ShiftLeft,
			KeyCode.None,
			KeyCode.Digit1,
			KeyCode.Digit2,
			KeyCode.Digit6,
			KeyCode.Digit3,
			KeyCode.Digit7,
			KeyCode.Digit8,
			KeyCode.Digit9,
			KeyCode.Digit4,
			KeyCode.Digit5,
			KeyCode.F5,
			KeyCode.F6,
			KeyCode.F7,
			KeyCode.F8, // FiveM Console
            KeyCode.F3,
			KeyCode.CapsLock,
			KeyCode.ArrowUp,
			KeyCode.ArrowDown,
			KeyCode.ArrowLeft,
			KeyCode.ArrowRight,
			KeyCode.Return, // KeyCode.MouseLeftClick
            KeyCode.Backspace, // KeyCode.Escape / KeyCode.MouseRightClick
            KeyCode.Delete,
			KeyCode.Space,
			KeyCode.MouseWheelDown,
			KeyCode.MouseWheelUp,
			KeyCode.KeyL,
			KeyCode.KeyG,
			KeyCode.MouseMiddleClick, // KeyCode.KeyE
            KeyCode.KeyF,
			KeyCode.KeyX,
			KeyCode.ArrowDown,
			KeyCode.ArrowUp,
			KeyCode.ArrowLeft,
			KeyCode.ArrowRight,
			KeyCode.Return,
			KeyCode.Tab,
			KeyCode.Space,
			KeyCode.Backspace,
			KeyCode.KeyAKeyD,
			KeyCode.KeyWKeyS,
			KeyCode.BracketLeft, // t_]%t_[
			KeyCode.MouseWheelUpDown,
			KeyCode.KeyP,
			KeyCode.Escape,
			KeyCode.Return, // KeyCode.Space / KeyCode.NumpadEnter
            KeyCode.Escape, // KeyCode.Backspace
            KeyCode.Space,
			KeyCode.Tab,
			KeyCode.KeyQ,
			KeyCode.KeyE,
			KeyCode.PageDown,
			KeyCode.PageUp,
			KeyCode.ShiftLeft,
			KeyCode.ControlLeft,
			KeyCode.Tab,
			KeyCode.Home,
			KeyCode.Home,
			KeyCode.Delete,
			KeyCode.Return,
			KeyCode.Space,
			KeyCode.CapsLock,
			KeyCode.KeyAKeyD,
			KeyCode.KeyWKeyS,
			KeyCode.MouseMoveLeftRight,
			KeyCode.MouseMoveUpDown,
			KeyCode.MouseRightClick,
			KeyCode.MouseLeftClick,
			KeyCode.ControlLeft,
			KeyCode.MouseRightClick,
			KeyCode.None,
			KeyCode.None,
			KeyCode.None,
			KeyCode.MouseLeftClick,
			KeyCode.None,
			KeyCode.None,
			KeyCode.KeyW,
			KeyCode.KeyS,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.KeyV,
			KeyCode.MouseLeftClick,
			KeyCode.MouseRightClick,
			KeyCode.MouseMoveLeftRight,
			KeyCode.MouseMoveUpDown,
			KeyCode.MouseWheelUp,
			KeyCode.MouseWheelDown,
			KeyCode.Backquote, // KeyCode.Tilde
            KeyCode.KeyM,
			KeyCode.KeyT,
			KeyCode.KeyY,
			KeyCode.None,
			KeyCode.None,
			KeyCode.KeyN,
			KeyCode.KeyR,
			KeyCode.KeyF,
			KeyCode.KeyX,
			KeyCode.KeyC,
			KeyCode.ShiftLeft,
			KeyCode.Return, // KeyCode.Space
            KeyCode.Delete,
			KeyCode.MouseLeftClick,
			KeyCode.None,
			KeyCode.None,
			KeyCode.None,
			KeyCode.MouseWheelUp,
			KeyCode.MouseWheelDown,
			KeyCode.KeyR,
			KeyCode.KeyQ,
			KeyCode.None,
			KeyCode.KeyD,
			KeyCode.KeyD,
			KeyCode.KeyS,
			KeyCode.KeyS,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveDown,
			KeyCode.MouseMoveDown,
			KeyCode.BracketLeft,
			KeyCode.BracketLeft,
			KeyCode.BracketLeft,
			KeyCode.BracketLeft,
			KeyCode.KeyD,
			KeyCode.KeyD,
			KeyCode.ControlLeft,
			KeyCode.ControlLeft,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveRight,
			KeyCode.MouseMoveRight,
			KeyCode.F1,
			KeyCode.F2,
			KeyCode.MouseMoveLeftRight,
			KeyCode.MouseMoveUpDown,
			KeyCode.MouseMoveUp,
			KeyCode.MouseMoveDown,
			KeyCode.MouseMoveLeft,
			KeyCode.MouseMoveRight,
			KeyCode.Delete,
			KeyCode.Delete,
			KeyCode.Space,
			KeyCode.ArrowDown,
			KeyCode.ArrowUp,
			KeyCode.KeyM,
			KeyCode.KeyS,
			KeyCode.KeyU,
			KeyCode.KeyH,
			KeyCode.KeyB,
			KeyCode.KeyN,
			KeyCode.ArrowRight,
			KeyCode.ArrowLeft,
			KeyCode.KeyT,
			KeyCode.KeyR,
			KeyCode.KeyK,
			KeyCode.BracketLeft,
			KeyCode.BracketRight,
			KeyCode.NumpadAdd,
			KeyCode.NumpadSubtract,
			KeyCode.PageUp,
			KeyCode.PageDown,
			KeyCode.F5,
			KeyCode.KeyC,
			KeyCode.KeyV,
			KeyCode.Space,
			KeyCode.Escape,
			KeyCode.KeyX,
			KeyCode.KeyC,
			KeyCode.KeyV,
			KeyCode.ControlLeft,
			KeyCode.F5,
			KeyCode.Space,
			KeyCode.MouseLeftClick,
			KeyCode.MouseRightClick,
			KeyCode.Space, // KeyCode.MouseRightClick
            KeyCode.MouseMoveUpDown,
			KeyCode.MouseMoveLeftRight,
			KeyCode.MouseWheelUpDown,
			KeyCode.MouseWheelUp,
			KeyCode.MouseWheelDown,
			KeyCode.KeyX,
			KeyCode.KeyA,
			KeyCode.KeyD,
			KeyCode.ShiftLeft,
			KeyCode.ControlLeft,
			KeyCode.KeyAKeyD,
			KeyCode.LeftShiftLeftControl,
			KeyCode.F11,
			KeyCode.KeyX,
			KeyCode.MouseLeftClick,
			KeyCode.MouseRightClick,
			KeyCode.MouseMiddleClick,
			KeyCode.Tab,
			KeyCode.KeyE,
			KeyCode.KeyE,
			KeyCode.ShiftLeft,
			KeyCode.Space,
			KeyCode.KeyX,
			KeyCode.KeyE,
			KeyCode.KeyE,
			KeyCode.KeyX
		};

		[SuppressMessage("ReSharper", "StringLiteralTypo")]
		public static List<string> ControlNativeNames = new List<string> {
			"INPUT_NEXT_CAMERA",
			"INPUT_LOOK_LR",
			"INPUT_LOOK_UD",
			"INPUT_LOOK_UP_ONLY",
			"INPUT_LOOK_DOWN_ONLY",
			"INPUT_LOOK_LEFT_ONLY",
			"INPUT_LOOK_RIGHT_ONLY",
			"INPUT_CINEMATIC_SLOWMO",
			"INPUT_SCRIPTED_FLY_UD",
			"INPUT_SCRIPTED_FLY_LR",
			"INPUT_SCRIPTED_FLY_ZUP",
			"INPUT_SCRIPTED_FLY_ZDOWN",
			"INPUT_WEAPON_WHEEL_UD",
			"INPUT_WEAPON_WHEEL_LR",
			"INPUT_WEAPON_WHEEL_NEXT",
			"INPUT_WEAPON_WHEEL_PREV",
			"INPUT_SELECT_NEXT_WEAPON",
			"INPUT_SELECT_PREV_WEAPON",
			"INPUT_SKIP_CUTSCENE",
			"INPUT_CHARACTER_WHEEL",
			"INPUT_MULTIPLAYER_INFO",
			"INPUT_SPRINT",
			"INPUT_JUMP",
			"INPUT_ENTER",
			"INPUT_ATTACK",
			"INPUT_AIM",
			"INPUT_LOOK_BEHIND",
			"INPUT_PHONE",
			"INPUT_SPECIAL_ABILITY",
			"INPUT_SPECIAL_ABILITY_SECONDARY",
			"INPUT_MOVE_LR",
			"INPUT_MOVE_UD",
			"INPUT_MOVE_UP_ONLY",
			"INPUT_MOVE_DOWN_ONLY",
			"INPUT_MOVE_LEFT_ONLY",
			"INPUT_MOVE_RIGHT_ONLY",
			"INPUT_DUCK",
			"INPUT_SELECT_WEAPON",
			"INPUT_PICKUP",
			"INPUT_SNIPER_ZOOM",
			"INPUT_SNIPER_ZOOM_IN_ONLY",
			"INPUT_SNIPER_ZOOM_OUT_ONLY",
			"INPUT_SNIPER_ZOOM_IN_SECONDARY",
			"INPUT_SNIPER_ZOOM_OUT_SECONDARY",
			"INPUT_COVER",
			"INPUT_RELOAD",
			"INPUT_TALK",
			"INPUT_DETONATE",
			"INPUT_HUD_SPECIAL",
			"INPUT_ARREST",
			"INPUT_ACCURATE_AIM",
			"INPUT_CONTEXT",
			"INPUT_CONTEXT_SECONDARY",
			"INPUT_WEAPON_SPECIAL",
			"INPUT_WEAPON_SPECIAL_TWO",
			"INPUT_DIVE",
			"INPUT_DROP_WEAPON",
			"INPUT_DROP_AMMO",
			"INPUT_THROW_GRENADE",
			"INPUT_VEH_MOVE_LR",
			"INPUT_VEH_MOVE_UD",
			"INPUT_VEH_MOVE_UP_ONLY",
			"INPUT_VEH_MOVE_DOWN_ONLY",
			"INPUT_VEH_MOVE_LEFT_ONLY",
			"INPUT_VEH_MOVE_RIGHT_ONLY",
			"INPUT_VEH_SPECIAL",
			"INPUT_VEH_GUN_LR",
			"INPUT_VEH_GUN_UD",
			"INPUT_VEH_AIM",
			"INPUT_VEH_ATTACK",
			"INPUT_VEH_ATTACK2",
			"INPUT_VEH_ACCELERATE",
			"INPUT_VEH_BRAKE",
			"INPUT_VEH_DUCK",
			"INPUT_VEH_HEADLIGHT",
			"INPUT_VEH_EXIT",
			"INPUT_VEH_HANDBRAKE",
			"INPUT_VEH_HOTWIRE_LEFT",
			"INPUT_VEH_HOTWIRE_RIGHT",
			"INPUT_VEH_LOOK_BEHIND",
			"INPUT_VEH_CIN_CAM",
			"INPUT_VEH_NEXT_RADIO",
			"INPUT_VEH_PREV_RADIO",
			"INPUT_VEH_NEXT_RADIO_TRACK",
			"INPUT_VEH_PREV_RADIO_TRACK",
			"INPUT_VEH_RADIO_WHEEL",
			"INPUT_VEH_HORN",
			"INPUT_VEH_FLY_THROTTLE_UP",
			"INPUT_VEH_FLY_THROTTLE_DOWN",
			"INPUT_VEH_FLY_YAW_LEFT",
			"INPUT_VEH_FLY_YAW_RIGHT",
			"INPUT_VEH_PASSENGER_AIM",
			"INPUT_VEH_PASSENGER_ATTACK",
			"INPUT_VEH_SPECIAL_ABILITY_FRANKLIN",
			"INPUT_VEH_STUNT_UD",
			"INPUT_VEH_CINEMATIC_UD",
			"INPUT_VEH_CINEMATIC_UP_ONLY",
			"INPUT_VEH_CINEMATIC_DOWN_ONLY",
			"INPUT_VEH_CINEMATIC_LR",
			"INPUT_VEH_SELECT_NEXT_WEAPON",
			"INPUT_VEH_SELECT_PREV_WEAPON",
			"INPUT_VEH_ROOF",
			"INPUT_VEH_JUMP",
			"INPUT_VEH_GRAPPLING_HOOK",
			"INPUT_VEH_SHUFFLE",
			"INPUT_VEH_DROP_PROJECTILE",
			"INPUT_VEH_MOUSE_CONTROL_OVERRIDE",
			"INPUT_VEH_FLY_ROLL_LR",
			"INPUT_VEH_FLY_ROLL_LEFT_ONLY",
			"INPUT_VEH_FLY_ROLL_RIGHT_ONLY",
			"INPUT_VEH_FLY_PITCH_UD",
			"INPUT_VEH_FLY_PITCH_UP_ONLY",
			"INPUT_VEH_FLY_PITCH_DOWN_ONLY",
			"INPUT_VEH_FLY_UNDERCARRIAGE",
			"INPUT_VEH_FLY_ATTACK",
			"INPUT_VEH_FLY_SELECT_NEXT_WEAPON",
			"INPUT_VEH_FLY_SELECT_PREV_WEAPON",
			"INPUT_VEH_FLY_SELECT_TARGET_LEFT",
			"INPUT_VEH_FLY_SELECT_TARGET_RIGHT",
			"INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE",
			"INPUT_VEH_FLY_DUCK",
			"INPUT_VEH_FLY_ATTACK_CAMERA",
			"INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE",
			"INPUT_VEH_SUB_TURN_LR",
			"INPUT_VEH_SUB_TURN_LEFT_ONLY",
			"INPUT_VEH_SUB_TURN_RIGHT_ONLY",
			"INPUT_VEH_SUB_PITCH_UD",
			"INPUT_VEH_SUB_PITCH_UP_ONLY",
			"INPUT_VEH_SUB_PITCH_DOWN_ONLY",
			"INPUT_VEH_SUB_THROTTLE_UP",
			"INPUT_VEH_SUB_THROTTLE_DOWN",
			"INPUT_VEH_SUB_ASCEND",
			"INPUT_VEH_SUB_DESCEND",
			"INPUT_VEH_SUB_TURN_HARD_LEFT",
			"INPUT_VEH_SUB_TURN_HARD_RIGHT",
			"INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE",
			"INPUT_VEH_PUSHBIKE_PEDAL",
			"INPUT_VEH_PUSHBIKE_SPRINT",
			"INPUT_VEH_PUSHBIKE_FRONT_BRAKE",
			"INPUT_VEH_PUSHBIKE_REAR_BRAKE",
			"INPUT_MELEE_ATTACK_LIGHT",
			"INPUT_MELEE_ATTACK_HEAVY",
			"INPUT_MELEE_ATTACK_ALTERNATE",
			"INPUT_MELEE_BLOCK",
			"INPUT_PARACHUTE_DEPLOY",
			"INPUT_PARACHUTE_DETACH",
			"INPUT_PARACHUTE_TURN_LR",
			"INPUT_PARACHUTE_TURN_LEFT_ONLY",
			"INPUT_PARACHUTE_TURN_RIGHT_ONLY",
			"INPUT_PARACHUTE_PITCH_UD",
			"INPUT_PARACHUTE_PITCH_UP_ONLY",
			"INPUT_PARACHUTE_PITCH_DOWN_ONLY",
			"INPUT_PARACHUTE_BRAKE_LEFT",
			"INPUT_PARACHUTE_BRAKE_RIGHT",
			"INPUT_PARACHUTE_SMOKE",
			"INPUT_PARACHUTE_PRECISION_LANDING",
			"INPUT_MAP",
			"INPUT_SELECT_WEAPON_UNARMED",
			"INPUT_SELECT_WEAPON_MELEE",
			"INPUT_SELECT_WEAPON_HANDGUN",
			"INPUT_SELECT_WEAPON_SHOTGUN",
			"INPUT_SELECT_WEAPON_SMG",
			"INPUT_SELECT_WEAPON_AUTO_RIFLE",
			"INPUT_SELECT_WEAPON_SNIPER",
			"INPUT_SELECT_WEAPON_HEAVY",
			"INPUT_SELECT_WEAPON_SPECIAL",
			"INPUT_SELECT_CHARACTER_MICHAEL",
			"INPUT_SELECT_CHARACTER_FRANKLIN",
			"INPUT_SELECT_CHARACTER_TREVOR",
			"INPUT_SELECT_CHARACTER_MULTIPLAYER",
			"INPUT_SAVE_REPLAY_CLIP",
			"INPUT_SPECIAL_ABILITY_PC",
			"INPUT_CELLPHONE_UP",
			"INPUT_CELLPHONE_DOWN",
			"INPUT_CELLPHONE_LEFT",
			"INPUT_CELLPHONE_RIGHT",
			"INPUT_CELLPHONE_SELECT",
			"INPUT_CELLPHONE_CANCEL",
			"INPUT_CELLPHONE_OPTION",
			"INPUT_CELLPHONE_EXTRA_OPTION",
			"INPUT_CELLPHONE_SCROLL_FORWARD",
			"INPUT_CELLPHONE_SCROLL_BACKWARD",
			"INPUT_CELLPHONE_CAMERA_FOCUS_LOCK",
			"INPUT_CELLPHONE_CAMERA_GRID",
			"INPUT_CELLPHONE_CAMERA_SELFIE",
			"INPUT_CELLPHONE_CAMERA_DOF",
			"INPUT_CELLPHONE_CAMERA_EXPRESSION",
			"INPUT_FRONTEND_DOWN",
			"INPUT_FRONTEND_UP",
			"INPUT_FRONTEND_LEFT",
			"INPUT_FRONTEND_RIGHT",
			"INPUT_FRONTEND_RDOWN",
			"INPUT_FRONTEND_RUP",
			"INPUT_FRONTEND_RLEFT",
			"INPUT_FRONTEND_RRIGHT",
			"INPUT_FRONTEND_AXIS_X",
			"INPUT_FRONTEND_AXIS_Y",
			"INPUT_FRONTEND_RIGHT_AXIS_X",
			"INPUT_FRONTEND_RIGHT_AXIS_Y",
			"INPUT_FRONTEND_PAUSE",
			"INPUT_FRONTEND_PAUSE_ALTERNATE",
			"INPUT_FRONTEND_ACCEPT",
			"INPUT_FRONTEND_CANCEL",
			"INPUT_FRONTEND_X",
			"INPUT_FRONTEND_Y",
			"INPUT_FRONTEND_LB",
			"INPUT_FRONTEND_RB",
			"INPUT_FRONTEND_LT",
			"INPUT_FRONTEND_RT",
			"INPUT_FRONTEND_LS",
			"INPUT_FRONTEND_RS",
			"INPUT_FRONTEND_LEADERBOARD",
			"INPUT_FRONTEND_SOCIAL_CLUB",
			"INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY",
			"INPUT_FRONTEND_DELETE",
			"INPUT_FRONTEND_ENDSCREEN_ACCEPT",
			"INPUT_FRONTEND_ENDSCREEN_EXPAND",
			"INPUT_FRONTEND_SELECT",
			"INPUT_SCRIPT_LEFT_AXIS_X",
			"INPUT_SCRIPT_LEFT_AXIS_Y",
			"INPUT_SCRIPT_RIGHT_AXIS_X",
			"INPUT_SCRIPT_RIGHT_AXIS_Y",
			"INPUT_SCRIPT_RUP",
			"INPUT_SCRIPT_RDOWN",
			"INPUT_SCRIPT_RLEFT",
			"INPUT_SCRIPT_RRIGHT",
			"INPUT_SCRIPT_LB",
			"INPUT_SCRIPT_RB",
			"INPUT_SCRIPT_LT",
			"INPUT_SCRIPT_RT",
			"INPUT_SCRIPT_LS",
			"INPUT_SCRIPT_RS",
			"INPUT_SCRIPT_PAD_UP",
			"INPUT_SCRIPT_PAD_DOWN",
			"INPUT_SCRIPT_PAD_LEFT",
			"INPUT_SCRIPT_PAD_RIGHT",
			"INPUT_SCRIPT_SELECT",
			"INPUT_CURSOR_ACCEPT",
			"INPUT_CURSOR_CANCEL",
			"INPUT_CURSOR_X",
			"INPUT_CURSOR_Y",
			"INPUT_CURSOR_SCROLL_UP",
			"INPUT_CURSOR_SCROLL_DOWN",
			"INPUT_ENTER_CHEAT_CODE",
			"INPUT_INTERACTION_MENU",
			"INPUT_MP_TEXT_CHAT_ALL",
			"INPUT_MP_TEXT_CHAT_TEAM",
			"INPUT_MP_TEXT_CHAT_FRIENDS",
			"INPUT_MP_TEXT_CHAT_CREW",
			"INPUT_PUSH_TO_TALK",
			"INPUT_CREATOR_LS",
			"INPUT_CREATOR_RS",
			"INPUT_CREATOR_LT",
			"INPUT_CREATOR_RT",
			"INPUT_CREATOR_MENU_TOGGLE",
			"INPUT_CREATOR_ACCEPT",
			"INPUT_CREATOR_DELETE",
			"INPUT_ATTACK2",
			"INPUT_RAPPEL_JUMP",
			"INPUT_RAPPEL_LONG_JUMP",
			"INPUT_RAPPEL_SMASH_WINDOW",
			"INPUT_PREV_WEAPON",
			"INPUT_NEXT_WEAPON",
			"INPUT_MELEE_ATTACK1",
			"INPUT_MELEE_ATTACK2",
			"INPUT_WHISTLE",
			"INPUT_MOVE_LEFT",
			"INPUT_MOVE_RIGHT",
			"INPUT_MOVE_UP",
			"INPUT_MOVE_DOWN",
			"INPUT_LOOK_LEFT",
			"INPUT_LOOK_RIGHT",
			"INPUT_LOOK_UP",
			"INPUT_LOOK_DOWN",
			"INPUT_SNIPER_ZOOM_IN",
			"INPUT_SNIPER_ZOOM_OUT",
			"INPUT_SNIPER_ZOOM_IN_ALTERNATE",
			"INPUT_SNIPER_ZOOM_OUT_ALTERNATE",
			"INPUT_VEH_MOVE_LEFT",
			"INPUT_VEH_MOVE_RIGHT",
			"INPUT_VEH_MOVE_UP",
			"INPUT_VEH_MOVE_DOWN",
			"INPUT_VEH_GUN_LEFT",
			"INPUT_VEH_GUN_RIGHT",
			"INPUT_VEH_GUN_UP",
			"INPUT_VEH_GUN_DOWN",
			"INPUT_VEH_LOOK_LEFT",
			"INPUT_VEH_LOOK_RIGHT",
			"INPUT_REPLAY_START_STOP_RECORDING",
			"INPUT_REPLAY_START_STOP_RECORDING_SECONDARY",
			"INPUT_SCALED_LOOK_LR",
			"INPUT_SCALED_LOOK_UD",
			"INPUT_SCALED_LOOK_UP_ONLY",
			"INPUT_SCALED_LOOK_DOWN_ONLY",
			"INPUT_SCALED_LOOK_LEFT_ONLY",
			"INPUT_SCALED_LOOK_RIGHT_ONLY",
			"INPUT_REPLAY_MARKER_DELETE",
			"INPUT_REPLAY_CLIP_DELETE",
			"INPUT_REPLAY_PAUSE",
			"INPUT_REPLAY_REWIND",
			"INPUT_REPLAY_FFWD",
			"INPUT_REPLAY_NEWMARKER",
			"INPUT_REPLAY_RECORD",
			"INPUT_REPLAY_SCREENSHOT",
			"INPUT_REPLAY_HIDEHUD",
			"INPUT_REPLAY_STARTPOINT",
			"INPUT_REPLAY_ENDPOINT",
			"INPUT_REPLAY_ADVANCE",
			"INPUT_REPLAY_BACK",
			"INPUT_REPLAY_TOOLS",
			"INPUT_REPLAY_RESTART",
			"INPUT_REPLAY_SHOWHOTKEY",
			"INPUT_REPLAY_CYCLEMARKERLEFT",
			"INPUT_REPLAY_CYCLEMARKERRIGHT",
			"INPUT_REPLAY_FOVINCREASE",
			"INPUT_REPLAY_FOVDECREASE",
			"INPUT_REPLAY_CAMERAUP",
			"INPUT_REPLAY_CAMERADOWN",
			"INPUT_REPLAY_SAVE",
			"INPUT_REPLAY_TOGGLETIME",
			"INPUT_REPLAY_TOGGLETIPS",
			"INPUT_REPLAY_PREVIEW",
			"INPUT_REPLAY_TOGGLE_TIMELINE",
			"INPUT_REPLAY_TIMELINE_PICKUP_CLIP",
			"INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP",
			"INPUT_REPLAY_TIMELINE_PLACE_CLIP",
			"INPUT_REPLAY_CTRL",
			"INPUT_REPLAY_TIMELINE_SAVE",
			"INPUT_REPLAY_PREVIEW_AUDIO",
			"INPUT_VEH_DRIVE_LOOK",
			"INPUT_VEH_DRIVE_LOOK2",
			"INPUT_VEH_FLY_ATTACK2",
			"INPUT_RADIO_WHEEL_UD",
			"INPUT_RADIO_WHEEL_LR",
			"INPUT_VEH_SLOWMO_UD",
			"INPUT_VEH_SLOWMO_UP_ONLY",
			"INPUT_VEH_SLOWMO_DOWN_ONLY",
			"INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE",
			"INPUT_VEH_HYDRAULICS_CONTROL_LEFT",
			"INPUT_VEH_HYDRAULICS_CONTROL_RIGHT",
			"INPUT_VEH_HYDRAULICS_CONTROL_UP",
			"INPUT_VEH_HYDRAULICS_CONTROL_DOWN",
			"INPUT_VEH_HYDRAULICS_CONTROL_UD",
			"INPUT_VEH_HYDRAULICS_CONTROL_LR",
			"INPUT_SWITCH_VISOR",
			"INPUT_VEH_MELEE_HOLD",
			"INPUT_VEH_MELEE_LEFT",
			"INPUT_VEH_MELEE_RIGHT",
			"INPUT_MAP_POI",
			"INPUT_REPLAY_SNAPMATIC_PHOTO",
			"INPUT_VEH_CAR_JUMP",
			"INPUT_VEH_ROCKET_BOOST",
			"INPUT_VEH_FLY_BOOST",
			"INPUT_VEH_PARACHUTE",
			"INPUT_VEH_BIKE_WINGS",
			"INPUT_VEH_FLY_BOMB_BAY",
			"INPUT_VEH_FLY_COUNTER",
			"INPUT_VEH_TRANSFORM"
		};

		public static List<string> ControlDisplayNames = new List<string>
		{
			"Next Camera",
			"Look Left/Right",
			"Look Up/Down",
			"Look Up Only",
			"Look Down Only",
			"Look Left Only",
			"Look Right Only",
			"Cinematic Slow Motion",
			"Fly Up/Down",
			"Fly Left/Right",
			"Scripted Fly Z Up",
			"Scripted Fly Z Down",
			"Weapon Wheel Up/Down",
			"Weapon Wheel Left/Right",
			"Weapon Wheel Next",
			"Weapon Wheel Prev",
			"Select Next Weapon",
			"Select Prev Weapon",
			"Skip Cutscene",
			"Character Wheel",
			"Multiplayer Info",
			"Sprint",
			"Jump",
			"Enter",
			"Attack",
			"Aim",
			"Look Behind",
			"Phone",
			"Special Ability",
			"Special Ability Secondary",
			"Move Left/Right",
			"Move Up/Down",
			"Move Up Only",
			"Move Down Only",
			"Move Left Only",
			"Move Right Only",
			"Duck",
			"Select Weapon",
			"Pickup",
			"Sniper Zoom",
			"Sniper Zoom In Only",
			"Sniper Zoom Out Only",
			"Sniper Zoom In Secondary",
			"Sniper Zoom Out Secondary",
			"Cover",
			"Reload",
			"Talk",
			"Detonate",
			"HUDSpecial",
			"Arrest",
			"Accurate Aim",
			"Context",
			"Context Secondary",
			"Weapon Special",
			"Weapon Special Secondary",
			"Dive",
			"Drop Weapon",
			"Drop Ammo",
			"Throw Grenade",
			"Vehicle Move Left/Right",
			"Vehicle Move Up/Down",
			"Vehicle Move Up Only",
			"Vehicle Move Down Only",
			"Vehicle Move Left Only",
			"Vehicle Move Right Only",
			"Vehicle Special",
			"Vehicle Gun Left/Right",
			"Vehicle Gun Up/Down",
			"Vehicle Aim",
			"Vehicle Attack",
			"Vehicle Attack Secondary",
			"Vehicle Accelerate",
			"Vehicle Brake",
			"Vehicle Duck",
			"Vehicle Headlight",
			"Vehicle Exit",
			"Vehicle Handbrake",
			"Vehicle Hotwire Left",
			"Vehicle Hotwire Right",
			"Vehicle Look Behind",
			"Vehicle Cin Cam",
			"Vehicle Next Radio Station",
			"Vehicle Prev Radio Station",
			"Vehicle Next Radio Track",
			"Vehicle Prev Radio Track",
			"Vehicle Radio Wheel",
			"Vehicle Horn",
			"Vehicle Fly Throttle Up",
			"Vehicle Fly Throttle Down",
			"Vehicle Fly Yaw Left",
			"Vehicle Fly Yaw Right",
			"Vehicle Passenger Aim",
			"Vehicle Passenger Attack",
			"Vehicle Special Ability Franklin",
			"Vehicle Stunt Up/Down",
			"Vehicle Cinematic Up/Down",
			"Vehicle Cinematic Up Only",
			"Vehicle Cinematic Down Only",
			"Vehicle Cinematic Left/Right",
			"Vehicle Select Next Weapon",
			"Vehicle Select Prev Weapon",
			"Vehicle Roof",
			"Vehicle Jump",
			"Vehicle Grappling Hook",
			"Vehicle Shuffle",
			"Vehicle Drop Projectile",
			"Vehicle Mouse Control Override",
			"Vehicle Fly Roll Left/Right",
			"Vehicle Fly Roll Left Only",
			"Vehicle Fly Roll Right Only",
			"Vehicle Fly Pitch Up/Down",
			"Vehicle Fly Pitch Up Only",
			"Vehicle Fly Pitch Down Only",
			"Vehicle Fly Under Carriage",
			"Vehicle Fly Attack",
			"Vehicle Fly Select Next Weapon",
			"Vehicle Fly Select Prev Weapon",
			"Vehicle Fly Select Target Left",
			"Vehicle Fly Select Target Right",
			"Vehicle Fly Vertical Flight Mode",
			"Vehicle Fly Duck",
			"Vehicle Fly Attack Camera",
			"Vehicle Fly Mouse Control Override",
			"Vehicle Sub Turn Left/Right",
			"Vehicle Sub Turn Left Only",
			"Vehicle Sub Turn Right Only",
			"Vehicle Sub Pitch Up/Down",
			"Vehicle Sub Pitch Up Only",
			"Vehicle Sub Pitch Down Only",
			"Vehicle Sub Throttle Up",
			"Vehicle Sub Throttle Down",
			"Vehicle Sub Ascend",
			"Vehicle Sub Descend",
			"Vehicle Sub Turn Hard Left",
			"Vehicle Sub Turn Hard Right",
			"Vehicle Sub Mouse Control Override",
			"Vehicle Pushbike Pedal",
			"Vehicle Pushbike Sprint",
			"Vehicle Pushbike Front Brake",
			"Vehicle Pushbike Rear Brake",
			"Melee Attack Light",
			"Melee Attack Heavy",
			"Melee Attack Alternate",
			"Melee Block",
			"Parachute Deploy",
			"Parachute Detach",
			"Parachute Turn Left/Right",
			"Parachute Turn Left Only",
			"Parachute Turn Right Only",
			"Parachute Pitch Up/Down",
			"Parachute Pitch Up Only",
			"Parachute Pitch Down Only",
			"Parachute Brake Left",
			"Parachute Brake Right",
			"Parachute Smoke",
			"Parachute Precision Landing",
			"Map",
			"Select Weapon Unarmed",
			"Select Weapon Melee",
			"Select Weapon Handgun",
			"Select Weapon Shotgun",
			"Select Weapon Smg",
			"Select Weapon Auto Rifle",
			"Select Weapon Sniper",
			"Select Weapon Heavy",
			"Select Weapon Special",
			"Select Character Michael",
			"Select Character Franklin",
			"Select Character Trevor",
			"Select Character Multiplayer",
			"Save Replay Clip",
			"Special Ability PC",
			"Phone Up",
			"Phone Down",
			"Phone Left",
			"Phone Right",
			"Phone Select",
			"Phone Cancel",
			"Phone Option",
			"Phone Extra Option",
			"Phone Scroll Forward",
			"Phone Scroll Backward",
			"Phone Camera Focus Lock",
			"Phone Camera Grid",
			"Phone Camera Selfie",
			"Phone Camera DOF",
			"Phone Camera Expression",
			"Frontend Down",
			"Frontend Up",
			"Frontend Left",
			"Frontend Right",
			"Frontend R Down",
			"Frontend R Up",
			"Frontend R Left",
			"Frontend R Right",
			"Frontend Axis X",
			"Frontend Axis Y",
			"Frontend Right Axis X",
			"Frontend Right Axis Y",
			"Frontend Pause",
			"Frontend Pause Alternate",
			"Frontend Accept",
			"Frontend Cancel",
			"Frontend X",
			"Frontend Y",
			"Frontend Lb",
			"Frontend Rb",
			"Frontend Lt",
			"Frontend Rt",
			"Frontend Ls",
			"Frontend Rs",
			"Frontend Leaderboard",
			"Frontend Social Club",
			"Frontend Social Club Secondary",
			"Frontend Delete",
			"Frontend Endscreen Accept",
			"Frontend Endscreen Expand",
			"Frontend Select",
			"Script Left Axis X",
			"Script Left Axis Y",
			"Script Right Axis X",
			"Script Right Axis Y",
			"Script RUp",
			"Script RDown",
			"Script RLeft",
			"Script RRight",
			"Script LB",
			"Script RB",
			"Script LT",
			"Script RT",
			"Script LS",
			"Script RS",
			"Script Pad Up",
			"Script Pad Down",
			"Script Pad Left",
			"Script Pad Right",
			"Script Select",
			"Cursor Accept",
			"Cursor Cancel",
			"Cursor X",
			"Cursor Y",
			"Cursor Scroll Up",
			"Cursor Scroll Down",
			"Enter Cheat Code",
			"Interaction Menu",
			"Mp Text Chat All",
			"Mp Text Chat Team",
			"Mp Text Chat Friends",
			"Mp Text Chat Crew",
			"Push To Talk",
			"Creator LS",
			"Creator RS",
			"Creator LT",
			"Creator RT",
			"Creator Menu Toggle",
			"Creator Accept",
			"Creator Delete",
			"Attack2",
			"Rappel Jump",
			"Rappel Long Jump",
			"Rappel Smash Window",
			"Prev Weapon",
			"Next Weapon",
			"Melee Attack1",
			"Melee Attack2",
			"Whistle",
			"Move Left",
			"Move Right",
			"Move Up",
			"Move Down",
			"Look Left",
			"Look Right",
			"Look Up",
			"Look Down",
			"Sniper Zoom In",
			"Sniper Zoom Out",
			"Sniper Zoom In Alternate",
			"Sniper Zoom Out Alternate",
			"Vehicle Move Left",
			"Vehicle Move Right",
			"Vehicle Move Up",
			"Vehicle Move Down",
			"Vehicle Gun Left",
			"Vehicle Gun Right",
			"Vehicle Gun Up",
			"Vehicle Gun Down",
			"Vehicle Look Left",
			"Vehicle Look Right",
			"Replay Start Stop Recording",
			"Replay Start Stop Recording Secondary",
			"Scaled Look Left/Right",
			"Scaled Look Up/Down",
			"Scaled Look Up Only",
			"Scaled Look Down Only",
			"Scaled Look Left Only",
			"Scaled Look Right Only",
			"Replay Marker Delete",
			"Replay Clip Delete",
			"Replay Pause",
			"Replay Rewind",
			"Replay Fast Forward",
			"Replay New Marker",
			"Replay Record",
			"Replay Screenshot",
			"Replay Hide HUD",
			"Replay Start Point",
			"Replay Endpoint",
			"Replay Advance",
			"Replay Back",
			"Replay Tools",
			"Replay Restart",
			"Replay Show Hotkey",
			"Replay Cycle Marker Left",
			"Replay Cycle Marker Right",
			"Replay FOVIncrease",
			"Replay FOVDecrease",
			"Replay Camera Up",
			"Replay Camera Down",
			"Replay Save",
			"Replay Toggle Time",
			"Replay Toggle Tips",
			"Replay Preview",
			"Replay Toggle Timeline",
			"Replay Timeline Pickup Clip",
			"Replay Timeline Duplicate Clip",
			"Replay Timeline Place Clip",
			"Replay Ctrl",
			"Replay Timeline Save",
			"Replay Preview Audio",
			"Vehicle Drive Look",
			"Vehicle Drive Look2",
			"Vehicle Fly Attack2",
			"Radio Wheel Up/Down",
			"Radio Wheel Left/Right",
			"Vehicle Slow Mo Up/Down",
			"Vehicle Slow Mo Up Only",
			"Vehicle Slow Mo Down Only",
			"Vehicle Hydraulics Control Toggle",
			"Vehicle Hydraulics Control Left",
			"Vehicle Hydraulics Control Right",
			"Vehicle Hydraulics Control Up",
			"Vehicle Hydraulics Control Down",
			"Vehicle Hydraulics Control Up/Down",
			"Vehicle Hydraulics Control Left/Right",
			"Switch Visor",
			"Vehicle Melee Hold",
			"Vehicle Melee Left",
			"Vehicle Melee Right",
			"Map Point Of Interest",
			"Replay Snapmatic Photo",
			"Vehicle Car Jump",
			"Vehicle Rocket Boost",
			"Vehicle Fly Boost",
			"Vehicle Parachute",
			"Vehicle Bike Wings",
			"Vehicle Fly Bomb Bay",
			"Vehicle Fly Counter",
			"Vehicle Fly Transform"
		};

		public static Dictionary<KeyCode, string> KeyCodeDisplayNames = new Dictionary<KeyCode, string>
		{
			{ KeyCode.Unknown, "Unknown" },
			{ KeyCode.None, "None" },
			{ KeyCode.Backspace, "Backspace" },
			{ KeyCode.Tab, "Tab" },
			{ KeyCode.Return, "Return" },
			{ KeyCode.Pause, "Pause" },
			{ KeyCode.Escape, "Escape" },
			{ KeyCode.Space, "Space" },
			{ KeyCode.Digit1, "1" },
			{ KeyCode.Digit2, "2" },
			{ KeyCode.Digit3, "3" },
			{ KeyCode.Digit4, "4" },
			{ KeyCode.Digit5, "5" },
			{ KeyCode.Digit6, "6" },
			{ KeyCode.Digit7, "7" },
			{ KeyCode.Digit8, "8" },
			{ KeyCode.Digit9, "9" },
			{ KeyCode.Digit0, "0" },
			{ KeyCode.KeyA, "A" },
			{ KeyCode.KeyB, "B" },
			{ KeyCode.KeyC, "C" },
			{ KeyCode.KeyD, "D" },
			{ KeyCode.KeyE, "E" },
			{ KeyCode.KeyF, "F" },
			{ KeyCode.KeyG, "G" },
			{ KeyCode.KeyH, "H" },
			{ KeyCode.KeyI, "I" },
			{ KeyCode.KeyJ, "J" },
			{ KeyCode.KeyK, "K" },
			{ KeyCode.KeyL, "L" },
			{ KeyCode.KeyM, "M" },
			{ KeyCode.KeyN, "N" },
			{ KeyCode.KeyO, "O" },
			{ KeyCode.KeyP, "P" },
			{ KeyCode.KeyQ, "Q" },
			{ KeyCode.KeyR, "R" },
			{ KeyCode.KeyS, "S" },
			{ KeyCode.KeyT, "T" },
			{ KeyCode.KeyU, "U" },
			{ KeyCode.KeyV, "V" },
			{ KeyCode.KeyW, "W" },
			{ KeyCode.KeyX, "X" },
			{ KeyCode.KeyY, "Y" },
			{ KeyCode.KeyZ, "Z" },
			{ KeyCode.Backquote, "Backquote" },
			{ KeyCode.Minus, "Minus" },
			{ KeyCode.Equal, "Equal" },
			{ KeyCode.BracketLeft, "Bracket Left" },
			{ KeyCode.BracketRight, "Bracket Right" },
			{ KeyCode.Semicolon, "Semicolon" },
			{ KeyCode.Quote, "Quote" },
			{ KeyCode.Backslash, "Backslash" },
			{ KeyCode.Comma, "Comma" },
			{ KeyCode.Period, "Period" },
			{ KeyCode.Slash, "Slash" },
			{ KeyCode.IntlBackslash, "Intl Backslash" },
			{ KeyCode.Numpad0, "Numpad 0" },
			{ KeyCode.Numpad1, "Numpad 1" },
			{ KeyCode.Numpad2, "Numpad 2" },
			{ KeyCode.Numpad3, "Numpad 3" },
			{ KeyCode.Numpad4, "Numpad 4" },
			{ KeyCode.Numpad5, "Numpad 5" },
			{ KeyCode.Numpad6, "Numpad 6" },
			{ KeyCode.Numpad7, "Numpad 7" },
			{ KeyCode.Numpad8, "Numpad 8" },
			{ KeyCode.Numpad9, "Numpad 9" },
			{ KeyCode.NumpadDecimal, "Numpad Decimal" },
			{ KeyCode.NumpadDivide, "Numpad Divide" },
			{ KeyCode.NumpadMultiply, "Numpad Multiply" },
			{ KeyCode.NumpadSubtract, "Numpad Subtract" },
			{ KeyCode.NumpadAdd, "Numpad Add" },
			{ KeyCode.NumpadEnter, "Numpad Enter" },
			{ KeyCode.NumpadEqual, "Numpad Equal" },
			{ KeyCode.NumLock, "Num Lock" },
			{ KeyCode.ArrowUp, "Arrow Up" },
			{ KeyCode.ArrowDown, "Arrow Down" },
			{ KeyCode.ArrowRight, "Arrow Right" },
			{ KeyCode.ArrowLeft, "Arrow Left" },
			{ KeyCode.Insert, "Insert" },
			{ KeyCode.Delete, "Delete" },
			{ KeyCode.Home, "Home" },
			{ KeyCode.End, "End" },
			{ KeyCode.PageUp, "Page Up" },
			{ KeyCode.PageDown, "Page Down" },
			{ KeyCode.F1, "F1" },
			{ KeyCode.F2, "F2" },
			{ KeyCode.F3, "F3" },
			{ KeyCode.F4, "F4" },
			{ KeyCode.F5, "F5" },
			{ KeyCode.F6, "F6" },
			{ KeyCode.F7, "F7" },
			{ KeyCode.F8, "F8" },
			{ KeyCode.F9, "F9" },
			{ KeyCode.F10, "F10" },
			{ KeyCode.F11, "F11" },
			{ KeyCode.F12, "F12" },
			{ KeyCode.F13, "F13" },
			{ KeyCode.F14, "F14" },
			{ KeyCode.F15, "F15" },
			{ KeyCode.F16, "F16" },
			{ KeyCode.F17, "F17" },
			{ KeyCode.F18, "F18" },
			{ KeyCode.F19, "F19" },
			{ KeyCode.F20, "F20" },
			{ KeyCode.F21, "F21" },
			{ KeyCode.F22, "F22" },
			{ KeyCode.F23, "F23" },
			{ KeyCode.F24, "F24" },
			{ KeyCode.CapsLock, "Caps Lock" },
			{ KeyCode.ScrollLock, "Scroll Lock" },
			{ KeyCode.PrintScreen, "Print Screen" },
			{ KeyCode.ShiftLeft, "Shift Left" },
			{ KeyCode.ShiftRight, "Shift Right" },
			{ KeyCode.ControlLeft, "Control Left" },
			{ KeyCode.ControlRight, "Control Right" },
			{ KeyCode.AltLeft, "Alt Left" },
			{ KeyCode.AltRight, "Alt Right" },
			{ KeyCode.MetaLeft, "Meta Left" },
			{ KeyCode.MetaRight, "Meta Right" },
			{ KeyCode.ContextMenu, "Context Menu" },
			{ KeyCode.MouseLeftClick, "Mouse Left Click" },
			{ KeyCode.MouseRightClick, "Mouse Right Click" },
			{ KeyCode.MouseMiddleClick, "Mouse Middle Click" },
			{ KeyCode.MouseWheelUp, "Mouse Wheel Up" },
			{ KeyCode.MouseWheelDown, "Mouse Wheel Down" },
			{ KeyCode.MouseWheelUpDown, "Mouse Wheel Up/Down" },
			{ KeyCode.MouseMoveUp, "Mouse Move Up" },
			{ KeyCode.MouseMoveDown, "Mouse Move Down" },
			{ KeyCode.MouseMoveUpDown, "Mouse Move Up/Down" },
			{ KeyCode.MouseMoveLeft, "Mouse Move Left" },
			{ KeyCode.MouseMoveRight, "Mouse Move Right" },
			{ KeyCode.MouseMoveLeftRight, "Mouse Move Left/Right" },

			{ KeyCode.KeyWKeyS, "S/W" },
			{ KeyCode.KeyAKeyD, "A/D" },
			{ KeyCode.LeftShiftLeftControl, "Left Shift/Left Control" },
			{ KeyCode.Numpad4Numpad6, "Numpad 4/Numpad 6" },
			{ KeyCode.Numpad8Numpad5, "Numpad 8/Numpad 5" }
		};

		public static List<string> ButtonCodeDisplayNames = new List<string>
		{
			"None",
			"A",
			"B",
			"X",
			"Y",
			"Left Trigger",
			"Right Trigger",
			"Left Button",
			"Right Button",
			"Left 3",
			"Right 3",
			"Start",
			"Back",
			"Left Stick",
			"Right Stick",
			"Dpad Up",
			"Dpad Down",
			"Dpad Left",
			"Dpad Right"
		};

		public static Dictionary<string, KeyCode> ScaleformKeyCodeMappings = new Dictionary<string, KeyCode>
		{
			{ "b_-1", KeyCode.Unknown }, // Correct?
			{ "b_995", KeyCode.Unknown }, // Correct?

			{ "b_100", KeyCode.MouseLeftClick },
			{ "b_101", KeyCode.MouseRightClick },
			{ "b_102", KeyCode.MouseMiddleClick },
			{ "b_108", KeyCode.MouseMoveLeft },
			{ "b_109", KeyCode.MouseMoveRight },
			{ "b_110", KeyCode.MouseMoveUp },
			{ "b_111", KeyCode.MouseMoveDown },
			{ "b_112", KeyCode.MouseMoveLeftRight },
			{ "b_113", KeyCode.MouseMoveUpDown },
			{ "b_115", KeyCode.MouseWheelUp },
			{ "b_116", KeyCode.MouseWheelDown },
			{ "b_117", KeyCode.MouseWheelUpDown },

			{ "b_130", KeyCode.NumpadSubtract },
			{ "b_131", KeyCode.NumpadAdd },
			{ "b_132", KeyCode.NumpadDecimal },
			{ "b_133", KeyCode.NumpadDivide },
			{ "b_134", KeyCode.NumpadMultiply },
			{ "b_135", KeyCode.NumpadEnter },
			{ "b_136", KeyCode.Numpad0 },
			{ "b_137", KeyCode.Numpad1 },
			{ "b_138", KeyCode.Numpad2 },
			{ "b_139", KeyCode.Numpad3 },
			{ "b_140", KeyCode.Numpad4 },
			{ "b_141", KeyCode.Numpad5 },
			{ "b_142", KeyCode.Numpad6 },
			{ "b_143", KeyCode.Numpad7 },
			{ "b_144", KeyCode.Numpad8 },
			{ "b_145", KeyCode.Numpad9 },
			{ "b_146", KeyCode.NumpadEqual },
			{ "b_170", KeyCode.F1 },
			{ "b_171", KeyCode.F2 },
			{ "b_172", KeyCode.F3 },
			{ "b_173", KeyCode.F4 },
			{ "b_174", KeyCode.F5 },
			{ "b_175", KeyCode.F6 },
			{ "b_176", KeyCode.F7 },
			{ "b_177", KeyCode.F8 },
			{ "b_178", KeyCode.F9 },
			{ "b_179", KeyCode.F10 },
			{ "b_180", KeyCode.F11 },
			{ "b_181", KeyCode.F12 },
			{ "b_182", KeyCode.F13 },
			{ "b_183", KeyCode.F14 },
			{ "b_184", KeyCode.F15 },
			{ "b_185", KeyCode.F16 },
			{ "b_186", KeyCode.F17 },
			{ "b_187", KeyCode.F18 },
			{ "b_188", KeyCode.F19 },
			{ "b_189", KeyCode.F20 },
			{ "b_190", KeyCode.F21 },
			{ "b_191", KeyCode.F22 },
			{ "b_192", KeyCode.F23 },
			{ "b_193", KeyCode.F24 },
			{ "b_194", KeyCode.ArrowUp },
			{ "b_195", KeyCode.ArrowDown },
			{ "b_196", KeyCode.ArrowLeft },
			{ "b_197", KeyCode.ArrowRight },
			{ "b_198", KeyCode.Delete },
			{ "b_199", KeyCode.Escape },
			{ "b_200", KeyCode.Insert },
			{ "b_201", KeyCode.End },
			{ "b_1000", KeyCode.ShiftLeft },
			{ "b_1001", KeyCode.ShiftRight },
			{ "b_1002", KeyCode.Tab },
			{ "b_1003", KeyCode.Return },
			{ "b_1004", KeyCode.Backspace },
			{ "b_1005", KeyCode.PrintScreen },
			{ "b_1006", KeyCode.ScrollLock },
			{ "b_1007", KeyCode.Pause },
			{ "b_1008", KeyCode.Home },
			{ "b_1009", KeyCode.PageUp },
			{ "b_1010", KeyCode.PageDown },
			{ "b_1011", KeyCode.NumLock },
			{ "b_1012", KeyCode.CapsLock },
			{ "b_1013", KeyCode.ControlLeft },
			{ "b_1014", KeyCode.ControlRight },
			{ "b_1015", KeyCode.AltLeft },
			{ "b_1016", KeyCode.AltRight },
			{ "b_1017", KeyCode.ContextMenu },
			{ "b_1018", KeyCode.MetaLeft },
			{ "b_1019", KeyCode.MetaRight },
			{ "b_2000", KeyCode.Space },
			{ "t_+", KeyCode.Equal },
			{ "t_-", KeyCode.Minus },
			{ "t_,", KeyCode.Comma },
			{ "t_;", KeyCode.Semicolon },
			{ "t_.", KeyCode.Period },
			{ "t_[", KeyCode.BracketLeft },
			{ "t_]", KeyCode.BracketRight },
			{ "t_`", KeyCode.Backquote },
			{ "t_=", KeyCode.Equal },
			{ "t_0", KeyCode.Digit0 },
			{ "t_1", KeyCode.Digit1 },
			{ "t_2", KeyCode.Digit2 },
			{ "t_3", KeyCode.Digit3 },
			{ "t_4", KeyCode.Digit4 },
			{ "t_5", KeyCode.Digit5 },
			{ "t_6", KeyCode.Digit6 },
			{ "t_7", KeyCode.Digit7 },
			{ "t_8", KeyCode.Digit8 },
			{ "t_9", KeyCode.Digit9 },
			{ "t_A", KeyCode.KeyA },
			{ "t_B", KeyCode.KeyB },
			{ "t_C", KeyCode.KeyC },
			{ "t_D", KeyCode.KeyD },
			{ "t_E", KeyCode.KeyE },
			{ "t_F", KeyCode.KeyF },
			{ "t_G", KeyCode.KeyG },
			{ "t_H", KeyCode.KeyH },
			{ "t_I", KeyCode.KeyI },
			{ "t_J", KeyCode.KeyJ },
			{ "t_K", KeyCode.KeyK },
			{ "t_L", KeyCode.KeyL },
			{ "t_M", KeyCode.KeyM },
			{ "t_N", KeyCode.KeyN },
			{ "t_O", KeyCode.KeyO },
			{ "t_P", KeyCode.KeyP },
			{ "t_Q", KeyCode.KeyQ },
			{ "t_R", KeyCode.KeyR },
			{ "t_S", KeyCode.KeyS },
			{ "t_T", KeyCode.KeyT },
			{ "t_U", KeyCode.KeyU },
			{ "t_V", KeyCode.KeyV },
			{ "t_W", KeyCode.KeyW },
			{ "t_X", KeyCode.KeyX },
			{ "t_Y", KeyCode.KeyY },
			{ "t_Z", KeyCode.KeyZ },

			{ "t_S%t_W", KeyCode.KeyWKeyS },
			{ "t_D%t_A", KeyCode.KeyAKeyD },
			{ "b_1013%b_1000", KeyCode.LeftShiftLeftControl },
			{ "b_142%b_140", KeyCode.Numpad4Numpad6 },
			{ "b_141%b_144", KeyCode.Numpad8Numpad5 }
		};

		public static InputMethod LastInputMethod => API.IsInputDisabled(2) ? InputMethod.MouseKeyboard : InputMethod.Controller;

		public static TimeSpan TimeSinceLastInput => TimeSpan.FromMilliseconds(API.GetTimeSinceLastInput(0));

		public static bool IsControlEnabled(InputControl control)
		{
			return API.IsControlEnabled(0, (int)control);
		}

		public static void DisableControl(InputControl control)
		{
			API.DisableControlAction(0, (int)control, true);
		}

		public static void EnableControl(InputControl control)
		{
			API.DisableControlAction(0, (int)control, false);
		}

		public static bool IsControlModifierPressed(InputModifier modifier)
		{
			if (modifier == InputModifier.Any) return true;

			var bitMask = ModifierFlagToValue.Where(m => Game.IsControlPressed(0, (Control)m.Value)).Aggregate<KeyValuePair<InputModifier, int>, InputModifier>(0, (current, m) => current | m.Key);

			return bitMask == modifier;
		}

		public static bool IsAnyControlJustPressed(InputMethod method = InputMethod.Any)
		{
			return Enum.GetValues(typeof(InputControl)).Cast<InputControl>().Any(value => IsControlJustPressed(value, InputModifier.None, method));
		}

		public static bool IsControlPressed(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return API.IsDisabledControlPressed(0, (int)control) && IsControlModifierPressed(modifier) && LastInputMethod.HasFlag(method);
		}

		public static bool IsControlJustPressed(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return API.IsDisabledControlJustPressed(0, (int)control) && IsControlModifierPressed(modifier) && LastInputMethod.HasFlag(method);
		}

		public static bool IsControlJustReleased(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return API.IsDisabledControlJustReleased(0, (int)control) && IsControlModifierPressed(modifier) && LastInputMethod.HasFlag(method);
		}

		public static bool IsDisabledControlPressed(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return IsControlPressed(control, modifier, method) && API.IsControlEnabled(0, (int)control);
		}

		public static bool IsDisabledControlJustPressed(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return IsControlJustPressed(control, modifier, method) && API.IsControlEnabled(0, (int)control);
		}

		public static bool IsDisabledControlJustReleased(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return IsControlJustReleased(control, modifier, method) && API.IsControlEnabled(0, (int)control);
		}

		public static bool IsEnabledControlPressed(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return API.IsControlPressed(0, (int)control) && IsControlModifierPressed(modifier) && LastInputMethod.HasFlag(method);
		}

		public static bool IsEnabledControlJustPressed(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return API.IsControlJustPressed(0, (int)control) && IsControlModifierPressed(modifier) && LastInputMethod.HasFlag(method);
		}

		public static bool IsEnabledControlJustReleased(InputControl control, InputModifier modifier = InputModifier.None, InputMethod method = InputMethod.Any)
		{
			return API.IsControlJustReleased(0, (int)control) && IsControlModifierPressed(modifier) && LastInputMethod.HasFlag(method);
		}
	}
}
